=== dotBlueShoes/XMLClasses/Mateusz_Strumillo_242539.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
xmlns:types="types"
vc:minVersion="1.1"
>

	<xs:include schemaLocation="information.xsd"/> <!-- Ta sama przestrzeń nazw - namespace  -->
	<xs:import namespace="types" schemaLocation="types.xsd"/> <!-- poprzez namespace mówie że w tym miejscu będzie miał inną przestrzeń nazw  -->

	<xs:attributeGroup name="atribEmployee">
		<xs:attribute name="id" type="types:id" use="required" />
		<xs:attribute name="position" type="types:position" use="required" />
		<xs:attribute name="ref-desk" type="types:id" use="required" />
		<xs:attribute name="isSuspended" type="xs:boolean" use="optional" />
	</xs:attributeGroup>

	<xs:simpleType name="stringList">
 		<xs:list itemType="types:stringElem"/>
	</xs:simpleType>

	<xs:group name = "elemPC">
		<xs:sequence>
			<xs:element name="PC">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="OS" type="types:bigLetterStringExtra" />
						<xs:element name="Program">
							<xs:complexType>
								<xs:all>
									<xs:element name="Name" type="types:bigLetterStringExtra" />
									<xs:element name="Version" type="xs:string" />
									<xs:element name="ReleaseDate" minOccurs="0">
										<!--
										<xs:alternative test="@kind='string'" type="OtherType"/>
										<xs:alternative type="DefaultType"/>
										-->
									</xs:element>
								</xs:all>
							</xs:complexType>
						</xs:element>
						<xs:element name="Software" type="stringList"></xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:choice>
				<xs:element name="Printer" minOccurs="0" />
				<xs:element name="FaxMachine" minOccurs="0" />
			</xs:choice>
			<xs:element name="Scanner" minOccurs="0" />
		</xs:sequence>
	</xs:group>
	
	// 2. name="Name" type="types:bigLetterString"
	// 3. name="Surname" type="types:bigLetterString"
	// 4. name="PersonalID" base="types:personalID"
	// 5. name="DateOfBirth" type="xs:date" 
	// 6. name="DateOfEmployment" type="xs:date"
	// 7. name="ShirtSize" minOccurs="0" memberTypes="types:sizeByNumber types:sizeByName"
	// 8. name="Address"
	// 	<xs:sequence>
	//  	<xs:element name="Country" type="xs:string" />
	//  	<xs:element name="City" type="types:bigLetterString" />
	//  	<xs:element name="Street" type="types:bigLetterString" />
	//  	<xs:element name="Number" type="xs:string" />
	//  	<xs:element name="ZIPCode" type="types:ZIPCode" />
	//  </xs:sequence>
	// 9. name="Salary"
	// <xs:sequence>
	// <xs:element name="BeforeTax" type="types:salary" />
	// <xs:element name="AfterTax" type="types:salary" />
	// </xs:sequence>
	// 10. <xs:attribute name="currency" type="types:currency" use="required"/>
	// 11. <xs:element name="IsTemporary" minOccurs="0" />
	// 12. <xs:attributeGroup ref="atribEmployee"/>
	// 13.
	// <xs:keyref name="key" refer="deskKey">
	// <xs:selector xpath="GameDevBusiness/Employees/Employee"/>
	// <xs:field xpath="@ref-desk"/>
	// </xs:keyref>
	
	// 14. DESKS ....

	<xs:element name="GameDevBusiness">
		<xs:complexType>
			<xs:sequence>

				<xs:element name="Information" type="tInformation"/>

				<xs:element name="Employees">
					<xs:complexType>
						<xs:sequence>

							<xs:element name="Employee" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Name" type="types:bigLetterString" />
										<xs:element name="Surname" type="types:bigLetterString" />
										<xs:element name="PersonalID">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="types:personalID">
														<xs:attribute name="nation" type="types:nation" use="required"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="DateOfBirth" type="xs:date" />
										<xs:element name="DateOfEmployment" type="xs:date"/>
										<xs:element name="ShirtSize" minOccurs="0">
											<xs:simpleType>
												<xs:union memberTypes="types:sizeByNumber types:sizeByName" />
											</xs:simpleType>
										</xs:element>
										<xs:element name="Address">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Country" type="xs:string" />
													<xs:element name="City" type="types:bigLetterString" />
													<xs:element name="Street" type="types:bigLetterString" />
													<xs:element name="Number" type="xs:string" />
													<xs:element name="ZIPCode" type="types:ZIPCode" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="Salary">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="BeforeTax" type="types:salary" />
													<xs:element name="AfterTax" type="types:salary" />
												</xs:sequence>
												<xs:attribute name="currency" type="types:currency" use="required"/>
											</xs:complexType>
										</xs:element>
										<xs:element name="IsTemporary" minOccurs="0" />
									</xs:sequence>
									<xs:attributeGroup ref="atribEmployee"/>
								</xs:complexType>
								<xs:keyref name="key" refer="deskKey">
									<xs:selector xpath="GameDevBusiness/Employees/Employee"/>
									<xs:field xpath="@ref-desk"/>
								</xs:keyref>
							</xs:element>
						</xs:sequence>
					</xs:complexType>

					<xs:key name="deskKey">
						<xs:selector xpath="GameDevBusiness/Desks/Desk"/>
						<xs:field xpath="@id"/>
					</xs:key>

				</xs:element>

				<xs:element name="Desks">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Desk" maxOccurs="unbounded">
								<xs:complexType>
									<xs:group ref="elemPC"/>
									<xs:attribute name="id" type="types:id" use="required" />
									<xs:attribute name="type" type="types:type" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== dotBlueShoes/XMLClasses/Mateusz_Strumillo_242539.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="style.css"?>
<GameDevBusiness xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="Mateusz_Strumillo_242539.xsd">

	<Information>
		<Autor>Mateusz Strumiłło 242539</Autor>
		<Date>2022-11-02T10:20:15</Date>
	</Information>

	<Employees>
	
		<Employee id="1" position="Programmer" ref-desk="1" isSuspended="true"> 	<!-- id: Unikalny, nie pusty klucz, position: Jedna z predefiniowanych nie pustych wartości jak "Programmer" -->
			<Name>Adam</Name> 														<!-- Ciąg znaków zaczynający się dużą literą (nie pusty) -->
			<Surname>Nowak</Surname> 												<!-- Ciąg znaków zaczynający się dużą literą (nie pusty) -->
			<PersonalID nation="Poland">12312312312</PersonalID> 					<!-- Ciąg liczb o rozmiarze 11 liczb -->
			<DateOfBirth>1995-08-04</DateOfBirth>									<!-- Format daty dd/mm/year -->
			<DateOfEmployment>2016-11-02</DateOfEmployment> 						<!-- Format daty dd/mm/year -->
			<ShirtSize>medium</ShirtSize>
			<Address>
				<Country>Poland</Country> 											<!-- Ciąg znaków zaczynający się dużą literą (nie pusty) -->
				<City>Lodz</City> 													<!-- Ciąg znaków zaczynający się dużą literą (nie pusty) -->
				<Street>Nowa</Street> 												<!-- Ciąg znaków zaczynający się dużą literą (nie pusty) -->
				<Number>41</Number> 												<!-- Ciąg znaków wrażliwy na wielkość liter (nie pusty) -->
				<ZIPCode>94-101</ZIPCode> 											<!-- Ciąg 6 znakowy o formacie XX-XXX -->
			</Address>
			<Salary currency="PLN"> 												<!-- Jedna z predefiniowanych nie pustych wartości jak "PLN" -->
				<BeforeTax>2500.00</BeforeTax> 										<!-- Ciąg liczb z 2 cyfrową liczbą zmiennoprzecinkową (nie pusty) -->
				<AfterTax>2300.25</AfterTax> 										<!-- Ciąg liczb z 2 cyfrową liczbą zmiennoprzecinkową (nie pusty) -->
			</Salary> 
			<IsTemporary/>
		</Employee>
		
		<Employee id="2" position="Desiner" ref-desk="2">
			<Name>Karol</Name>
			<Surname>Kowalski</Surname>
			<PersonalID nation="Poland">32132132132</PersonalID>
			<DateOfBirth>1998-05-13</DateOfBirth>
			<DateOfEmployment>2020-12-01</DateOfEmployment>
			<Address>
				<Country>Poland</Country>
				<City>Warszawa</City>
				<Street>Przyszkolna</Street>
				<Number>26</Number>
				<ZIPCode>95-505</ZIPCode>
			</Address>
			<Salary currency="PLN">
				<BeforeTax>2400.00</BeforeTax>
				<AfterTax>2250.50</AfterTax>
			</Salary>
		</Employee>

		<Employee id="3" position="Programmer" ref-desk="3">
			<Name>Tomasz</Name>
			<Surname>Nowak</Surname>
			<PersonalID nation="Poland">33322211132</PersonalID>
			<DateOfBirth>1997-05-13</DateOfBirth>
			<DateOfEmployment>2020-12-01</DateOfEmployment>
			<ShirtSize>39</ShirtSize>
			<Address>
				<Country>Poland</Country>
				<City>Warszawa</City>
				<Street>Nowoszkolna</Street>
				<Number>25</Number>
				<ZIPCode>95-505</ZIPCode>
			</Address>
			<Salary currency="PLN">
				<BeforeTax>2400.00</BeforeTax>
				<AfterTax>2250.50</AfterTax>
			</Salary>
		</Employee>

		<Employee id="4" position="Level-Designer" ref-desk="4">
			<Name>Adrian</Name>
			<Surname>Kowalski</Surname>
			<PersonalID nation="Poland">11122233312</PersonalID>
			<DateOfBirth>1996-05-13</DateOfBirth>
			<DateOfEmployment>2020-12-01</DateOfEmployment>
			<Address>
				<Country>Poland</Country>
				<City>Warszawa</City>
				<Street>Przyszkolna</Street>
				<Number>24</Number>
				<ZIPCode>95-505</ZIPCode>
			</Address>
			<Salary currency="PLN">
				<BeforeTax>2400.00</BeforeTax>
				<AfterTax>2250.50</AfterTax>
			</Salary>
		</Employee>

		<Employee id="5" position="Programmer" ref-desk="5">
			<Name>Milosz</Name>
			<Surname>Nowak</Surname>
			<PersonalID nation="Poland">11122233321</PersonalID>
			<DateOfBirth>1995-05-13</DateOfBirth>
			<DateOfEmployment>2020-12-01</DateOfEmployment>
			<Address>
				<Country>UK</Country>
				<City>London</City>
				<Street>Nowoszkolna</Street>
				<Number>23</Number>
				<ZIPCode>91-045</ZIPCode>
			</Address>
			<Salary currency="PLN">
				<BeforeTax>2500.00</BeforeTax>
				<AfterTax>2300.25</AfterTax> 
			</Salary>
		</Employee>

		<Employee id="6" position="Desiner" ref-desk="6">
			<Name>Kinga</Name>
			<Surname>Kowalski</Surname>
			<PersonalID nation="Poland">11122233322</PersonalID>
			<DateOfBirth>1994-05-13</DateOfBirth>
			<DateOfEmployment>2020-12-01</DateOfEmployment>
			<Address>
				<Country>Poland</Country>
				<City>Warszawa</City>
				<Street>Przyszkolna</Street>
				<Number>22</Number>
				<ZIPCode>95-505</ZIPCode>
			</Address>
			<Salary currency="PLN">
				<BeforeTax>2400.00</BeforeTax>
				<AfterTax>2250.50</AfterTax>
			</Salary>
			<IsTemporary/>
		</Employee>

		<Employee id="7" position="Desiner" ref-desk="7">
			<Name>Filip</Name>
			<Surname>Nowak</Surname>
			<PersonalID nation="Poland">11122233323</PersonalID>
			<DateOfBirth>1993-05-13</DateOfBirth>
			<DateOfEmployment>2020-12-01</DateOfEmployment>
			<Address>
				<Country>Poland</Country>
				<City>Warszawa</City>
				<Street>Przyszkolna</Street>
				<Number>26</Number>
				<ZIPCode>95-505</ZIPCode>
			</Address>
			<Salary currency="PLN">
				<BeforeTax>2400.00</BeforeTax>
				<AfterTax>2250.50</AfterTax>
			</Salary>
		</Employee>

		<Employee id="8" position="Programmer" ref-desk="8">
			<Name>Arek</Name>
			<Surname>Kowalski</Surname>
			<PersonalID nation="Poland">12345678912</PersonalID>
			<DateOfBirth>1993-05-13</DateOfBirth>
			<DateOfEmployment>2020-12-01</DateOfEmployment>
			<Address>
				<Country>UK</Country>
				<City>London</City>
				<Street>Nowoszkolna</Street>
				<Number>21</Number>
				<ZIPCode>91-045</ZIPCode>
			</Address>
			<Salary currency="PLN">
				<BeforeTax>2500.00</BeforeTax>
				<AfterTax>2300.25</AfterTax> 
			</Salary>
		</Employee>

		<Employee id="9" position="Desiner" ref-desk="9">
			<Name>Ola</Name>
			<Surname>Nowak</Surname>
			<PersonalID nation="Poland">98765432112</PersonalID>
			<DateOfBirth>1992-05-13</DateOfBirth>
			<DateOfEmployment>2020-12-01</DateOfEmployment>
			<Address>
				<Country>UK</Country>
				<City>London</City>
				<Street>Przyszkolna</Street>
				<Number>19</Number>
				<ZIPCode>91-045</ZIPCode>
			</Address>
			<Salary currency="PLN">
				<BeforeTax>2400.00</BeforeTax>
				<AfterTax>2250.50</AfterTax>
			</Salary>
		</Employee>

		<Employee id="10" position="Desiner" ref-desk="10">
			<Name>Wojtek</Name>
			<Surname>Kowalski</Surname>
			<PersonalID nation="Poland">99988877712</PersonalID>
			<DateOfBirth>1992-05-13</DateOfBirth>
			<DateOfEmployment>2020-12-01</DateOfEmployment>
			<Address>
				<Country>UK</Country>
				<City>London</City>
				<Street>Nowoszkolna</Street>
				<Number>26</Number>
				<ZIPCode>91-045</ZIPCode>
			</Address>
			<Salary currency="PLN">
				<BeforeTax>2400.00</BeforeTax>
				<AfterTax>2250.50</AfterTax>
			</Salary>
		</Employee>

		<Employee id="11" position="Programmer" ref-desk="11">
			<Name>Kuba</Name>
			<Surname>Nowak</Surname>
			<PersonalID nation="Poland">77889966111</PersonalID>
			<DateOfBirth>1998-05-13</DateOfBirth>
			<DateOfEmployment>2020-12-01</DateOfEmployment>
			<Address>
				<Country>UK</Country>
				<City>London</City>
				<Street>Przyszkolna</Street>
				<Number>18</Number>
				<ZIPCode>91-045</ZIPCode>
			</Address>
			<Salary currency="PLN">
				<BeforeTax>2400.00</BeforeTax>
				<AfterTax>2250.50</AfterTax>
			</Salary>
		</Employee>

		<Employee id="12" position="Desiner" ref-desk="12">
			<Name>Karol</Name>
			<Surname>Kowalski</Surname>
			<PersonalID nation="Poland">44411144421</PersonalID>
			<DateOfBirth>1998-05-13</DateOfBirth>
			<DateOfEmployment>2020-12-01</DateOfEmployment>
			<ShirtSize>large</ShirtSize>
			<Address>
				<Country>UK</Country>
				<City>London</City>
				<Street>Nowoszkolna</Street>
				<Number>26</Number>
				<ZIPCode>91-045</ZIPCode>
			</Address>
			<Salary currency="PLN">
				<BeforeTax>2500.00</BeforeTax>
				<AfterTax>2300.25</AfterTax> 
			</Salary>
		</Employee>

		<Employee id="13" position="Programmer" ref-desk="13">
			<Name>Rafal</Name>
			<Surname>Nowak</Surname>
			<PersonalID nation="Poland">77766655511</PersonalID>
			<DateOfBirth>1991-05-13</DateOfBirth>
			<DateOfEmployment>2020-12-01</DateOfEmployment>
			<Address>
				<Country>Poland</Country>
				<City>Warszawa</City>
				<Street>Przyszkolna</Street>
				<Number>17</Number>
				<ZIPCode>95-505</ZIPCode>
			</Address>
			<Salary currency="PLN">
				<BeforeTax>2400.00</BeforeTax>
				<AfterTax>2250.50</AfterTax>
			</Salary>
		</Employee>

		<Employee id="14" position="Desiner" ref-desk="14">
			<Name>Maciek</Name>
			<Surname>Kowalski</Surname>
			<PersonalID nation="Poland">55556664441</PersonalID>
			<DateOfBirth>1991-05-13</DateOfBirth>
			<DateOfEmployment>2020-12-01</DateOfEmployment>
			<Address>
				<Country>Poland</Country>
				<City>Warszawa</City>
				<Street>Nowoszkolna</Street>
				<Number>16</Number>
				<ZIPCode>95-505</ZIPCode>
			</Address>
			<Salary currency="PLN">
				<BeforeTax>2400.00</BeforeTax>
				<AfterTax>2250.50</AfterTax>
			</Salary>
		</Employee>

		<Employee id="15" position="Level-Designer" ref-desk="15">
			<Name>Macko</Name>
			<Surname>Nowak</Surname>
			<PersonalID nation="Poland">86786758581</PersonalID>
			<DateOfBirth>1995-05-13</DateOfBirth>
			<DateOfEmployment>2020-12-01</DateOfEmployment>
			<Address>
				<Country>UK</Country>
				<City>London</City>
				<Street>Przyszkolna</Street>
				<Number>15</Number>
				<ZIPCode>91-045</ZIPCode>
			</Address>
			<Salary currency="PLN">
				<BeforeTax>2500.00</BeforeTax>
				<AfterTax>2300.25</AfterTax> 
			</Salary>
		</Employee>

		<Employee id="16" position="Desiner" ref-desk="16">
			<Name>Mandaryn</Name>
			<Surname>Kowalski</Surname>
			<PersonalID nation="Poland">23621626312</PersonalID>
			<DateOfBirth>1995-05-13</DateOfBirth>
			<DateOfEmployment>2020-12-01</DateOfEmployment>
			<Address>
				<Country>Poland</Country>
				<City>Warszawa</City>
				<Street>Nowoszkolna</Street>
				<Number>14</Number>
